// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlogApp.Models
{
    public partial class Article
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(500)]
        public string Title { get; set; }

        [StringLength(1000)]
        public string Abstract { get; set; }

        public DateTime PublicationDate { get; set; }

        [StringLength(500)]
        public string Author { get; set; }

        public bool IsPublished { get; set; }

        public string Body { get; set; }
        [StringLength(1000)]

        public string Picture { get; set; }

        public int? CategoryId { get; set; }
        [StringLength(1000)]

        public string Keywords { get; set; }
        [StringLength(500)]

        public string PageTitle { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("Articles")]
        public virtual Category Category { get; set; }
    }
}